In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
import warnings

In [12]:
warnings.filterwarnings('ignore')

In [13]:
heart_ds = pd.read_csv("/Users/michaelperrine/Library/CloudStorage/OneDrive-Personal/Projects/heart_disease.csv")
heart_ds.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [14]:
heart_ds['Gender'] = heart_ds['Gender'].replace({'Male': 1, 'Female': 0})

In [24]:
heart_ds['Smoking'].replace({'Yes': 1, 'No': 0}, inplace=True)

In [20]:
heart_ds['Family Heart Disease'].replace({'Yes': 1, 'No': 0}, inplace=True)

In [23]:
heart_ds['Diabetes'].replace({'Yes': 1, 'No': 0}, inplace=True)

In [16]:
heart_ds['BMI'] = heart_ds['BMI'].round(2)

In [25]:
heart_ds.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,1.0,153.0,155.0,High,1.0,1.0,0.0,24.99,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,0.0,146.0,286.0,High,0.0,1.0,1.0,25.22,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,1.0,126.0,216.0,Low,0.0,0.0,0.0,29.86,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,0.0,122.0,293.0,High,1.0,1.0,0.0,24.13,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,1.0,166.0,242.0,Low,1.0,1.0,1.0,20.49,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No