In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
import warnings

In [12]:
warnings.filterwarnings('ignore')

In [13]:
heart_ds = pd.read_csv("/Users/michaelperrine/Library/CloudStorage/OneDrive-Personal/Projects/heart_disease.csv")
heart_ds.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,...,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,...,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,...,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,...,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,...,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No

In [34]:
le = LabelEncoder()

In [35]:
heart_ds['Exercise Habits'] = le.fit_transform(heart_ds['Exercise Habits'])

In [37]:
heart_ds['Alcohol Consumption'] = le.fit_transform(heart_ds['Alcohol Consumption'])

In [40]:
heart_ds['Gender'] = le.fit_transform(heart_ds['Gender'])

In [43]:
heart_ds['Smoking'] = le.fit_transform(heart_ds['Smoking'])

In [44]:
heart_ds['Family Heart Disease'] = le.fit_transform(heart_ds['Family Heart Disease'])

In [45]:
heart_ds['Diabetes'] = le.fit_transform(heart_ds['Diabetes'])

In [46]:
heart_ds['High Blood Pressure'] = le.fit_transform(heart_ds['High Blood Pressure'])

In [47]:
heart_ds['Low HDL Cholesterol'] = le.fit_transform(heart_ds['Low HDL Cholesterol'])

In [48]:
heart_ds['High LDL Cholesterol'] = le.fit_transform(heart_ds['High LDL Cholesterol'])

In [49]:
heart_ds['Stress Level'] = le.fit_transform(heart_ds['Stress Level'])

In [50]:
heart_ds['Sugar Consumption'] = le.fit_transform(heart_ds['Sugar Consumption'])

In [51]:
heart_ds['Heart Disease Status'] = le.fit_transform(heart_ds['Heart Disease Status'])

In [52]:
heart_ds['BMI'] = heart_ds['BMI'].round(2)

In [53]:
heart_ds.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,...,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,38,1,153.0,155.0,0,1,1,0,24.99,1,...,0,0,2,7.633228,2,342.0,NaN,12.969246,12.387250,0
1,51,0,146.0,286.0,0,0,1,1,25.22,0,...,0,2,0,8.744034,2,133.0,157.0,9.355389,19.298875,0
2,28,1,126.0,216.0,1,0,0,0,29.86,0,...,1,1,1,4.440440,1,393.0,92.0,12.709873,11.230926,0
3,14,0,122.0,293.0,0,1,1,0,24.13,1,...,1,1,0,5.249405,0,293.0,94.0,12.509046,5.961958,0
4,42,1,166.0,242.0,1,1,1,1,20.49,1,...,0,1,0,7.030971,0,263.0,154.0,10.381259,8.153887,0